export const ADDNEW_TODO = "ADDNEW_TODO";
export const ADDNEW_PRODUCT = "ADDNEW_PRODUCT";
export const GETALL_PRODUCTS = "GETALL_PRODUCTS";
export const UPDATE_PRODUCT = "UPDATE_PRODUCTS";
export const DELETE_PRODUCT = "DELETE_PRODUCTS";
